def print_lyrics():
    print("No, don’t think that religion is far away from love and life")
    print()
    print("And that by abandoning religion you’ll live and love what your heart loves")
    print()
    print("Or that the days will be better and you’ll see the Life - Dunya - as a rescuing shore")
    print()
    print("Your religion is a sea of hopes, a shore for the prettiest dreams")
    print()
    print("Religion isn’t what you think.. this is not allowed, that if forbidden")
    print()
    print("But Islam is really beautiful, that’s not Islam what you think!")
    print()
    print("All of its obligations guide us and call us for the good")
    print()
    print("It forbids us from every way that takes us to the evil.")
    print()
    print("And Allah is merciful and patient, He always calls for righteousness")
    print()
    print("In religion, there is prayers and greetings and also happiness and delight")
    print()
    print("And the religious is who you meet, and find him smiling and as sweet as light")
    print()
    print("He seeks to build up his Life - Dunya - and he has a delicate behavior and patient")
    print()
    print("Islam is a peace within us, it plants people’s love in us")
    print()
    print("Islam is a love ship, pushed by the best feeling")
    print()
    print("How beautiful life is, if we lived and made Islam the base")

print_lyrics()
